<?php
	$IsiframeActive = trim(Mage::getStoreConfig('shipping/internationalcheckout/iframe_active'));
	$merchant_id = trim(Mage::getStoreConfig('shipping/internationalcheckout/name_of_company'));
	$GSX_Localshipping_EXP = trim(Mage::getStoreConfig('shipping/internationalcheckout/local_shippingexp'));
	$GSX_Localshipping = trim(Mage::getStoreConfig('shipping/internationalcheckout/local_shipping')); 
	$GSX_restriction_attribute = trim(Mage::getStoreConfig('shipping/internationalcheckout/restriction_item')); 
	$sslActive = trim(Mage::getStoreConfig('shipping/internationalcheckout/developer_site')); 

	
	if($merchant_id != ""){
		$gc_url = $this->GC_URL;
	}else{
		$gc_url = "http://globalshopex.com/join_us.html";
	}	
	
	?>

<div class="col-main">
	<div class="page-title">
		<h1>International Checkout</h1>
	</div>
	<table id="shopping-cart-table" class="data-table cart-table" style="width: 710px">
		<tr>
			<td>
				<iframe id="Gsframe" name="Gsframe" style="" frameborder="0" scrolling="auto" height="1600px" width="710px" allowtransparency="true" >
				</iframe>
				<form name="frmPP" id="frmPP" method="post" action="https://globalshopex.com/iframe/InternationalCheckout.aspx" target="Gsframe"  >	
				<?php
					$session = Mage::getSingleton('checkout/session');
					$output = "";
					$i = 1;
					foreach ($session->getQuote()->getAllVisibleItems() as $item) {
						$item_ID = $item->getProductId();
						$_Product = Mage::getModel('catalog/product')->load($item_ID);
						$ProductPrice=$item->getPrice();
						$ProductPrice  =  substr ( $ProductPrice   , 0,strrpos($ProductPrice, ".") +3 ) ;
						$ProductWeight=$_Product->getWeight();
						$ProductWeight  =  substr ( $ProductWeight   , 0,strrpos($ProductWeight, ".") +3 ) ;
						if($ProductWeight=="") $ProductWeight="0";

						
						$output .= "<input type=\"hidden\" name=\"ProductSKU$i\" value=\"".$_Product->getSku()."\"/>\n";
						$output .= "<input type=\"hidden\" name=\"ProductDesc$i\" value=\"".$this->buildItemDescription($item)."\"/>\n";
						$output .= "<input type=\"hidden\" name=\"ProductLink$i\" value=\"".$this->getProductUrl($item)."\"/>\n";
						$output .= "<input type=\"hidden\" name=\"ProductQty$i\" value=\"".$item->getQty()."\"/>\n";
						$output .= "<input type=\"hidden\" name=\"ProductPrice$i\" value=\"".$ProductPrice ."\"/>\n";
						$output .= "<input type=\"hidden\" name=\"ProductSize$i\" value=\"".$this->getSize($item)."\"/>\n";
						$output .= "<input type=\"hidden\" name=\"ProductColor$i\" value=\"".$this->getColor($item)."\"/>\n";
						$output .= "<input type=\"hidden\" name=\"ProductWeight$i\" value=\"".$ProductWeight."\"/>\n";
						if($item->getCountry()!="")
							$output .= "<input type=\"hidden\" name=\"ProducCountry$i\" value=\"".$item->getCountry()."\"/>\n";
						if($this->getBrand($item)!="")
							$output .= "<input type=\"hidden\" name=\"ProductBrand$i\" value=\"".$this->getBrand($item)."\"/>\n";
						
						$attributes = Mage::getResourceModel('eav/entity_attribute_collection')
							  ->setEntityTypeFilter($_Product->getResource()->getTypeId())
							  ->addFieldToFilter('attribute_code', $GSX_restriction_attribute) 
							  ->load(false);
						
						$attribute = $attributes->getFirstItem()->setEntity($_Product->getResource());
						$manufac = $attribute->getSource()->getAllOptions(false);
						foreach ($manufac as $man) {
							$intshiping[$man['value']] = $man['label'];
						}
						
						
						if($_Product->getData($GSX_restriction_attribute) == '1')
							$output .= "<input type=\"hidden\" name=\"Restricted$i\" value='1'/>\n";
						$imgWidth = "";
						$imgHeight = "";
					
						if ($imgWidth == "" || $imgWidth <=0) {
							$imgWidth = 75;
						}
						$output .= "<input type=\"hidden\" name=\"ProductImage$i\" value=\"".$this->getProductThumbnail($item)->resize($imgWidth)."\"/>\n";
						$i++;
					}
					
					echo $output;
					
					if($GSX_Localshipping_EXP!="") $gsx_ls_exp = $GSX_Localshipping_EXP; else $gsx_ls_exp = "0";
					if($GSX_Localshipping!="") $gsx_ls = $GSX_Localshipping; else $gsx_ls = "0";
					
					$GSX_totals = $session->getQuote()->getData();
					$coupon_code = $GSX_totals['coupon_code'];
					$discount = $GSX_totals['subtotal'] - $GSX_totals['subtotal_with_discount'];
					$perc = ($discount * 100) / $GSX_totals['subtotal'];
					$perc = round($perc , 2);
					?>
					
					<input type="hidden" name="MerchantID" value="<?php echo $merchant_id; ?>" />   
					<input type="hidden" name="LocalShippingEXP" value="<?php echo $gsx_ls_exp; ?>" /> 
					<input type="hidden" name="LocalShipping" value="<?php echo $gsx_ls; ?>" />
					

				</form> 
			</td>
		</tr>
	</table>
</div>
<script language="javascript" type="text/javascript">
	 document.getElementById('frmPP').submit();
</script>