<?php
	
	$IsiframeActive = trim(Mage::getStoreConfig('shipping/internationalcheckout/iframe_active'));
	$merchant_id = trim(Mage::getStoreConfig('shipping/internationalcheckout/name_of_company'));
	$GSX_Localshipping_EXP = trim(Mage::getStoreConfig('shipping/internationalcheckout/local_shippingexp'));
	$GSX_Localshipping = trim(Mage::getStoreConfig('shipping/internationalcheckout/local_shipping')); 
	$GSX_restriction_attribute = trim(Mage::getStoreConfig('shipping/internationalcheckout/restriction_item')); 
	$developer_site = trim(Mage::getStoreConfig('shipping/internationalcheckout/developer_site')); 
	
	$gc_url = "http://globalshopex.com/join_us.html";	
	$showCartToCart=false;
	
	if($merchant_id != ""){
		$gc_url = $this->GC_URL;
		if ($IsiframeActive=='true' || $IsiframeActive==''){
			$urlIFrame=Mage::getBaseUrl();
			if($developer_site!='true' ){
				$urlIFrame=str_replace('http:','https:',Mage::getBaseUrl());
			}
			$urlIFrame= $urlIFrame."GSXInternationalCheckout/Checkout";
			}else{
			$urlIFrame=$gc_url;
			$showCartToCart=true;
		}
		}else{
		$showCartToCart=true;
	}
?>	

<?php
	if($showCartToCart){
	?>	
	<form name="gcForm" id="gcForm" method="post" action="<?php echo $gc_url;?>">
		
		<?php
			
			$session = Mage::getSingleton('checkout/session');
			$output = "";
			$i = 1;
			$imgWidth = 75;
			$imgHeight = 75;
			
			foreach ($session->getQuote()->getAllVisibleItems() as $item) {
				$item_ID = $item->getProductId();
				$_Product = Mage::getModel('catalog/product')->load($item_ID);
				$ProductPrice=$item->getPrice();
				$ProductPrice  =  substr ( $ProductPrice   , 0,strrpos($ProductPrice, ".") +3 ) ;
				$ProductWeight=$_Product->getWeight();
				$ProductWeight  =  substr ( $ProductWeight   , 0,strrpos($ProductWeight, ".") +3 ) ;
				
				if($ProductWeight=="") $ProductWeight="0";
				
				$output .= "<input type=\"hidden\" name=\"ProductSKU$i\" value=\"".$_Product->getSku()."\"/>\n";
				$output .= "<input type=\"hidden\" id=\"ProductDesc$i\" name=\"ProductDesc$i\" value=\"".$this->buildItemDescription($item)."\"/>\n";
				$output .= "<input type=\"hidden\" name=\"ProductLink$i\" value=\"".$this->getProductUrl($item)."\"/>\n";
				$output .= "<input type=\"hidden\" name=\"ProductQty$i\" value=\"".$item->getQty()."\"/>\n";
				$output .= "<input type=\"hidden\" name=\"ProductPrice$i\" value=\"".$ProductPrice ."\"/>\n";
				$output .= "<input type=\"hidden\" name=\"ProductSize$i\" value=\"".$this->getSize($item)."\"/>\n";
				$output .= "<input type=\"hidden\" name=\"ProductColor$i\" value=\"".$this->getColor($item)."\"/>\n";
				$output .= "<input type=\"hidden\" name=\"ProductWeight$i\" value=\"".$ProductWeight."\"/>\n";
				
				if($item->getCountry()!="")
				$output .= "<input type=\"hidden\" name=\"ProductCountry$i\" value=\"".$item->getCountry()."\"/>\n";
				if($item->getBrand($item)!="")
				$output .= "<input type=\"hidden\" name=\"ProductBrand$i\" value=\"".$this->getBrand($item)."\"/>\n";
				
				$attributes = Mage::getResourceModel('eav/entity_attribute_collection')
				->setEntityTypeFilter($_Product->getResource()->getTypeId())
				->addFieldToFilter('attribute_code', $GSX_restriction_attribute) 
				->load(false);
				
				$attribute = $attributes->getFirstItem()->setEntity($_Product->getResource());
				$manufac = $attribute->getSource()->getAllOptions(false);
				foreach ($manufac as $man) {
					$intshiping[$man['value']] = $man['label'];
				}
 
				
				if($_Product->getData($GSX_restriction_attribute) == '1')
					$output .= "<input type=\"hidden\" name=\"Restricted$i\" value='1'/>\n";
				
				$output .= "<input type=\"hidden\" name=\"ProductImage$i\" value=\"".$this->getProductThumbnail($item)->resize($imgWidth)."\"/>\n";
				$i++;
			}
			
			echo $output;
			
			if(isset($GSX_Localshipping_EXP)) $gsx_ls_exp = $GSX_Localshipping_EXP; else $gsx_ls_exp = "0";
			if(isset($GSX_Localshipping)) $gsx_ls = $GSX_Localshipping; else $gsx_ls = "0";
			
			$GSX_totals = $session->getQuote()->getData();
			$coupon_code = $GSX_totals['coupon_code'];
			$discount = $GSX_totals['subtotal'] - $GSX_totals['subtotal_with_discount'];
			$perc = ($discount * 100) / $GSX_totals['subtotal'];
			$perc = round($perc , 2);
		?>
		
		<input type="hidden" name="ODiscount" value="<?php echo $perc; ?>" /> 
		<input type="hidden" name="ODiscCode" value="<?php echo $coupon_code; ?>" /> 
		<input type="hidden" name="ODiscPerc" value="1" /> 
		<input type="hidden" name="MerchantID" value="<?php echo $merchant_id; ?>" />   
		<input type="hidden" name="LocalShippingEXP" value="<?php echo $gsx_ls_exp; ?>" /> 
		<input type="hidden" name="LocalShipping" value="<?php echo $gsx_ls; ?>" />
		<input type="hidden" name="PrefilledCart" value="<?php echo $this->helper('core/url')->getCurrentUrl();?>"/>
		
		<button title="<?php echo $this->__('Global Checkout') ?>" class="" <?php echo $this->buttonImagePath(); ?> type="submit"></button>	
	</form> 
	<?php
		}else{
	?>
<a href="<?php echo $urlIFrame ?>" title="<?php echo $this->__('Global Checkout') ?>" >
<div <?php echo $this->buttonImagePath(); ?>>	</div>
</a>
<?php
}
?>

